language: android
jdk: oraclejdk6
branches:
  only:
    - gradle

android:
  components:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-bcbbd656
script:
  - ./gradlew clean test