language: android
branches:
  only:
    - gradle

android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-bcbbd656

env:
  global:
    - TERM=dumb

script:
  - ./gradlew clean test