language: android

branches:
  only:
    - gradle

env:
  global:
    - TERM=dumb
    - ANDROID_SDK_VERSION="r23.0.2"

before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - tar -zxf android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  - echo yes | android update sdk --filter platform-tools,android-14 --no-ui --force

android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-bcbbd656
    - android-sdk-license-5be876d5

script:
  - ./gradlew clean test